### ISSUE TITLE
bugfix: priority to use openresty's cjson library

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#164]
Openresty has a built-in cjson library, but users may also install another version of cjson via luarocks, in which case we should give priority to the former.

**Comment by membphis** [comment]
The current reasonable search path is: deps -> apisix-lua -> openresty built-in -> standard Lua built-in.
In order to find the correct cjson library, you cannot have a cjson library in the deps directory.

**Comment by moonming** [comment]
https://github.com/iresty/apisix/pull/165 not consider RPM users

**Comment by membphis** [comment]
https://github.com/iresty/apisix/pull/165#discussion_r298492706

we can close it now.
