### ISSUE TITLE
能否支持zookeeper来做配置分发，流量分发

### ISSUE THREAD

**Issue by kissss** [iresty/apisix#172]
我也大量看过lua 和zk的资料，目前没有很好地方案让lua支持zk，目前我们的服务是通过zk注册，不太好维护2套发现服务

**Comment by membphis** [comment]
我觉得先让 apisix 支持不依赖任何外部组件，单纯通过配置 + API 控制的版本，这样 etcd 就可以是一个可选项，到时候能自然的支持 zookeeper 成为选项。
