### ISSUE TITLE
feature: support to reload local plugin without reload server.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#173]
apisix 需要有能力支持插件的热加载和卸载，尽量减少对服务重启的依赖。

Apisix needs to be able to support the hot loading and unloading of plugins, minimizing the dependency on service restarts.

这里有个最基本的问题，就是如何以事件方式通知到所有 worker 进程。允许不同 worker 监听不同端口，以此基础完成不同 worker 相互通信。

The most basic problem here is how to notify all worker processes by event. Allow different workers to listen to different ports, so that different workers can communicate with each other.

**Comment by moonming** [comment]
how about lua-resty-mlcache？

**Comment by membphis** [comment]
They are not powerful enough, and although they basically meet our needs, they will turn our synchronization delay into a lot.

A friend in Beijing is already trying to complete an independent listening port for each worker process, we can look forward to it.

**Comment by moonming** [comment]
fixed by https://github.com/iresty/apisix/commit/6963fbb6c0240b6826ea338f91e28c595896a92c, we can use admin api `/apisix/admin/plugins/reload` to reload plugins without reload server.
