### ISSUE TITLE
Call for APISIX Logo

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#195]
目前 apisix 还没有自己的 logo，欢迎大家贡献自己 idea。

先设计了一个初稿，大家可以参考。

Currently apisix does not have its own logo, welcome to contribute ideas.

First designed a draft, you can refer to it.

![image](https://user-images.githubusercontent.com/6814606/60582184-e69c6d80-9dba-11e9-9c96-c454be933e68.png)

**Comment by richardbmx** [comment]
@membphis  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project.

[My Portfolio](https://www.behance.net/richardcaseres)

**Comment by moonming** [comment]
@richardbmx welcome :)

**Comment by richardbmx** [comment]
@membphis  @moonming   I would like to present this proposal which is based on the main idea that you have to give a more personalized style for your project the letter A is used as the main icon I hope you like it if you want some change you just have to agree and I can do it with pleasure.

![logo141](https://user-images.githubusercontent.com/35604837/61173155-5948de00-a55d-11e9-9a89-cd3fc2e35681.png)

**Comment by xiaoyu87** [comment]
@membphis         
嗨，我叫孙雷，是一个用户界面设计师，我喜欢开源社区。看到要为apisix设计个logo ，很有兴趣。 APISIX 是一个基于云原生、高速可扩展的开源微服务网关节点实现，其自身主要优势是高性能和强大的扩展性。

基于这个内容，对现有logo设计提出自己的见解和改进设计方案。APISIX主要围绕A进行产品定位形象设计。突出高性能、强大轻快的产品品质。
改进现有logo的方案，包含两个方面。首先，上面的造型突出形象感，A的辨识明显；其次，抽取三角元素的特点，增加上扬的斜角，使造型更有轻快的动感。第二个方面，下面的品牌文字，加粗加强厚重感，与上面的造型呼应，整体感更融洽；其次，词组首字母的变化，与上面的造型相呼应，增加整体感。

Hi, my name is Sun Lei, I am a user interface designer. I like the open source community. I am very interested to see that I want to design a logo for apisix. APISIX is a cloud-based, high-speed and scalable open source microservice gateway node implementation. Its main advantages are high performance and powerful scalability.

Based on this content, I will present my own insights and improved design solutions for existing logo designs. APISIX mainly focuses on A for product positioning image design. Highlight high performance, strong and light product quality.
There are two aspects to improving the existing logo. First of all, the above style highlights the image, and the identification of A is obvious. Secondly, the characteristics of the triangular elements are extracted, and the upward angle is increased to make the shape more brisk. The second aspect, the following brand text, bold and thick sense, echoes the above shape, the overall sense is more harmonious; secondly, the change of the initials of the phrase, echoes the above shape, increasing the overall sense.

![image](https://user-images.githubusercontent.com/52855736/61179459-3b4eac80-a635-11e9-94c1-b3241bee3720.png)

**Comment by xiaoyu87** [comment]
@membphis
嗨，我叫孙雷，是一个用户界面设计师，我喜欢开源社区。看到要为apisix设计个logo ，很有兴趣。 APISIX 是一个基于云原生、高速可扩展的开源微服务网关节点实现，其自身主要优势是高性能和强大的扩展性。

基于这个内容，对现有logo设计提出自己的见解和改进设计方案。APISIX主要围绕A进行产品定位形象设计。突出高性能、强大轻快的产品品质。
改进现有logo的方案，包含两个方面。首先，上面的造型突出形象感，A的辨识明显；其次，抽取三角元素的特点，增加上扬的斜角，使造型更有轻快的动感。第二个方面，下面的品牌文字，加粗加强厚重感，与上面的造型呼应，整体感更融洽；其次，词组首字母的变化，与上面的造型相呼应，增加整体感。

Hi, my name is Sun Lei, I am a user interface designer. I like the open source community. I am very interested to see that I want to design a logo for apisix. APISIX is a cloud-based, high-speed and scalable open source microservice gateway node implementation. Its main advantages are high performance and powerful scalability.

Based on this content, I will present my own insights and improved design solutions for existing logo designs. APISIX mainly focuses on A for product positioning image design. Highlight high performance, strong and light product quality.
There are two aspects to improving the existing logo. First of all, the above style highlights the image, and the identification of A is obvious. Secondly, the characteristics of the triangular elements are extracted, and the upward angle is increased to make the shape more brisk. The second aspect, the following brand text, bold and thick sense, echoes the above shape, the overall sense is more harmonious; secondly, the change of the initials of the phrase, echoes the above shape, increasing the overall sense.

[APISIX-logo.jpg](url)

**Comment by xiaoyu87** [comment]
@membphis 
嗨，我叫孙雷，是一个用户界面设计师，我喜欢开源社区。看到要为apisix设计个logo ，很有兴趣。 APISIX 是一个基于云原生、高速可扩展的开源微服务网关节点实现，其自身主要优势是高性能和强大的扩展性。

基于这个内容，对现有logo设计提出自己的见解和改进设计方案。APISIX主要围绕A进行产品定位形象设计。突出高性能、强大轻快的产品品质。
改进现有logo的方案，包含两个方面。首先，上面的造型突出形象感，A的辨识明显；其次，抽取三角元素的特点，增加上扬的斜角，使造型更有轻快的动感。第二个方面，下面的品牌文字，加粗加强厚重感，与上面的造型呼应，整体感更融洽；其次，词组首字母的变化，与上面的造型相呼应，增加整体感。 

Hi, my name is Sun Lei, I am a user interface designer. I like the open source community. I am very interested to see that I want to design a logo for apisix. APISIX is a cloud-based, high-speed and scalable open source microservice gateway node implementation. Its main advantages are high performance and powerful scalability.

Based on this content, I will present my own insights and improved design solutions for existing logo designs. APISIX mainly focuses on A for product positioning image design. Highlight high performance, strong and light product quality.
There are two aspects to improving the existing logo. First of all, the above style highlights the image, and the identification of A is obvious. Secondly, the characteristics of the triangular elements are extracted, and the upward angle is increased to make the shape more brisk. The second aspect, the following brand text, bold and thick sense, echoes the above shape, the overall sense is more harmonious; secondly, the change of the initials of the phrase, echoes the above shape, increasing the overall sense.

![Uploading APISIX-logo.jpg…]()

**Comment by xiaoyu87** [comment]
@membphis 
嗨，我叫孙雷，是一个用户界面设计师，我喜欢开源社区。看到要为apisix设计个logo ，很有兴趣。 APISIX 是一个基于云原生、高速可扩展的开源微服务网关节点实现，其自身主要优势是高性能和强大的扩展性。

基于这个内容，对现有logo设计提出自己的见解和改进设计方案。APISIX主要围绕A进行产品定位形象设计。突出高性能、强大轻快的产品品质。
改进现有logo的方案，包含两个方面。首先，上面的造型突出形象感，A的辨识明显；其次，抽取三角元素的特点，增加上扬的斜角，使造型更有轻快的动感。第二个方面，下面的品牌文字，加粗加强厚重感，与上面的造型呼应，整体感更融洽；其次，词组首字母的变化，与上面的造型相呼应，增加整体感。

Hi, my name is Sun Lei, I am a user interface designer. I like the open source community. I am very interested to see that I want to design a logo for apisix. APISIX is a cloud-based, high-speed and scalable open source microservice gateway node implementation. Its main advantages are high performance and powerful scalability.

Based on this content, I will present my own insights and improved design solutions for existing logo designs. APISIX mainly focuses on A for product positioning image design. Highlight high performance, strong and light product quality.
There are two aspects to improving the existing logo. First of all, the above style highlights the image, and the identification of A is obvious. Secondly, the characteristics of the triangular elements are extracted, and the upward angle is increased to make the shape more brisk. The second aspect, the following brand text, bold and thick sense, echoes the above shape, the overall sense is more harmonious; secondly, the change of the initials of the phrase, echoes the above shape, increasing the overall sense.

![APISIX-logo](https://user-images.githubusercontent.com/52855736/61179907-5d4d2c80-a63f-11e9-869f-f2a796fe666c.jpg)

**Comment by moonming** [comment]
@xiaoyu87 I love this logo, but it is similar with https://www.channelnewsasia.com/news/international, can we do some changes? thanks.

**Comment by wind930** [comment]
When I saw that I was going to collect logos for apisix, I first thought about the tenon-mortise structure in China (http://www.sohu.com/a/256776296_674358).

It is more appropriate with the implication of api, and can reflect the ancient wisdom of China.

My time is limited, I just made a simple attempt, aiming to attract new ideas, welcome you to dedicate your creativity.

Here are a few simple design sketches. Welcome to make bricks.
![Uploading image.png…]()

**Comment by xiaoyu87** [comment]
@moonming Ok, I am editing

**Comment by xiaoyu87** [comment]
@membphis @moonming 
设计第二版
基于对APISIX logo定位形象设计分析。主体运用折线表现APISIX的原生、可扩展的网关节点内在形式，组成A的造型点明主意。另外翻转的折线设计增强了轻快的动感。整体与品牌文字配合，更加完整。

Design second edition
Based on the positioning of the APISIX logo image design analysis. The main body uses the polyline to express the intrinsic form of APISIX's native and extensible gateway nodes, and constitutes the shape of A. In addition, the inverted fold line design enhances the lightness of the movement. The overall cooperation with the brand text is more complete.

![APISIXlogo](https://user-images.githubusercontent.com/52855736/62005987-53faae80-b16d-11e9-96cc-9dba3470f5b2.png)

**Comment by membphis** [comment]
### png + white font

![logo-white](https://user-images.githubusercontent.com/6814606/76282441-a2ab2200-62d2-11ea-8eb4-47afd0fa36b4.png)

### png + black font

![logo-black](https://user-images.githubusercontent.com/6814606/76282454-adfe4d80-62d2-11ea-8013-bb96f53449bc.png)


### svg + black font

[apisix.svg.zip](https://github.com/apache/incubator-apisix/files/4310445/apisix.svg.zip)

**Comment by Caelebs** [comment]
svg format logo get √
