### ISSUE TITLE
doc: updated the benchmark result for tag v0.5

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#200]
![image](https://user-images.githubusercontent.com/6814606/60671840-969ad500-9ea6-11e9-906c-0d5a21ee0a30.png)

![image](https://user-images.githubusercontent.com/6814606/60671853-a1556a00-9ea6-11e9-932e-79e9bb1cb785.png)

**Comment by membphis** [comment]
here is original benchmark result: https://github.com/iresty/apisix/issues/118

**Comment by orangle** [comment]
Q: need to replace original document or add to original document ?
 i think need to replace

**Comment by moonming** [comment]
yes, you can replace the original document

orangleliu <notifications@github.com> 于2019年7月26日周五 下午6:44写道：

**Comment by membphis** [comment]
expired
