### ISSUE TITLE
win10+WSL+ubuntu18.04环境搭建

### ISSUE THREAD

**Issue by xewn** [iresty/apisix#214]
www@SKY-20190621OAP:~/work/apisix$ sudo make dev
./utils/update_nginx_conf_dev.sh
: not foundate_nginx_conf_dev.sh: 2: ./utils/update_nginx_conf_dev.sh:
: not foundate_nginx_conf_dev.sh: 4: ./utils/update_nginx_conf_dev.sh:
./utils/update_nginx_conf_dev.sh: 13: ./utils/update_nginx_conf_dev.sh: Syntax error: end of file unexpected (expecting "then")
Makefile:24: recipe for target 'dev' failed
make: *** [dev] Error 2

**Comment by moonming** [comment]
we did not test APISIX in windows10 and WSL, welcome PR to fix it.

**Comment by moonming** [comment]
consider to closed. if anyone wants to implement APISIX in win10+WSL, I will reopen it.
