### ISSUE TITLE
doc: how to run the test cases, chinese version.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#230]
missing document about how to run the test cases, that is useful for new developer.

**Comment by membphis** [comment]
added English version right now: https://github.com/iresty/apisix#test

**Comment by orangle** [comment]
follow  https://github.com/iresty/apisix#test ，but can not find test section

**Comment by membphis** [comment]
what is your problem? do you have fixed it? @orangle

**Comment by moonming** [comment]
@membphis https://github.com/iresty/apisix#test is a bad link, 404 not found. So where is the English version?

**Comment by membphis** [comment]
it seems @moonming  have move this section to `doc/dev-manual.md`.

original link: https://github.com/iresty/apisix/commit/a385ba6da2c7a6bbfc3819773eabe3b63a24c230#diff-04c6e90faac2675aa89e2176d2eec7d8
