### ISSUE TITLE
change: check the openresty version in Lua land.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#245]
here is current way:

https://github.com/iresty/apisix/commit/faeb07cadbcbcdad414c677c3094f2c1164809dc#diff-62edadffc237f13dc28a694080d293a8R251

we fetch the openresty version mainly by shell. Reduce external command line dependencies, such as in the docker environment, the system is minimized.

here is a code example:

```lua
local or_ver = shell('openresty -v 2>&1')
local res = compare(string.sub(or_ver, #"nginx version: openresty/"), "1.15.8.1")
if not res then
    error("failed")
end

print("success")
```

**Comment by membphis** [comment]
@soulsoul do you have any advice? ^_^

**Comment by soulsoul** [comment]
i agree   @membphis
