### ISSUE TITLE
add default values and test cases for health check.

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#266]
the health check does not have default values: https://github.com/iresty/apisix/blob/master/lua/apisix/core/schema.lua#L52, we need to add them following https://github.com/Kong/lua-resty-healthcheck/blob/master/lib/resty/healthcheck.lua#L1121

here is a example:
```
interval = {type = "integer", minimum = 1, default = 1}
```

and we need to add test cases for schema check for the health check, just like https://github.com/iresty/apisix/blob/master/t/plugin/limit-count.t#L221

**Comment by chnliyong** [comment]
Let me have a try！

**Comment by chnliyong** [comment]
@moonming  The default value of `interval` within `active` and `passive` in the `lua-resty-healthcheck` is `0` which means the `active` or `passive` check is disabled by default. 

As `default` is an annotation like keyword(https://json-schema.org/understanding-json-schema/reference/generic.html), `default: 0` won't conflict with `minimun: 1`, but this is strange intuitively！

**Comment by membphis** [comment]
here is the default value: https://github.com/Kong/lua-resty-healthcheck/blob/master/lib/resty/healthcheck.lua#L1121

I think we'd better keep same.
