### ISSUE TITLE
doc: Upstream

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/apisix#282]
Key is valid when using type `roundrobin` or `chash`?

![image](https://user-images.githubusercontent.com/2106987/61586465-39419c00-aba7-11e9-918f-cf9667610491.png)

**Comment by membphis** [comment]
document error, changed to: 该选项只有类型是 `chash` 才有效

**Comment by membphis** [comment]
@juzhiyuan welcome to submit a PR to fix this problem
