### ISSUE TITLE
confuse about https config

### ISSUE THREAD

**Issue by LazyMaple** [iresty/apisix#321]
i see apisix config node_ssl_listen param in `bin/apisix`(https://github.com/iresty/apisix/blob/master/bin/apisix#L333),
```
    local sys_conf = setmetatable({
            lua_path = package.path,
            lua_cpath = package.cpath,
            os_name = exec("uname"),
            apisix_lua_home = apisix_home,
            with_module_status = with_module_status,
            node_ssl_listen = 9443,     -- default value
        },
        {__index = yaml_conf.apisix}
    )
```
cause  node_ssl_listen = 9443,  yaml_conf.apisix.node_ssl_listen doesn't work,
it made node_ssl_listen become a hard code and can not config, is there a mistake or anything i get worng?

**Comment by moonming** [comment]
I think it's a bug. PR is welcome. @LazyMaple

**Comment by moonming** [comment]
@vkill @membphis please take a look

**Comment by membphis** [comment]
PR is welcome

**Comment by vkill** [comment]
Sorry, I found this bug very early.
