### ISSUE TITLE
suggestion about dashboard config

### ISSUE THREAD

**Issue by LazyMaple** [iresty/apisix#335]
dashborad project maybe better if it's source code rather than built files,
the backend url in dashborad project (https://github.com/iresty/apisix_dashboard_built) is http://39.97.63.215:9080/apisix/admin/, you can find it in *.js, such as 
https://raw.githubusercontent.com/iresty/apisix_dashboard_built/master/js/chunk-00c2fb87.513541fe.js.
How about set backend dashborad addr to be 127.0.0.1 or localhost? And had better not to open 39.97.63.215:9080 in public to avoid security problem

**Comment by moonming** [comment]
thanks for your report, the patch is on the way.

**Comment by moonming** [comment]
how about add dashborad built files and apisix in the same server? so we can remove the ip address in the dashborad built files.

**Comment by LazyMaple** [comment]
Yes, it's what i need now, thanks.

**Comment by moonming** [comment]
fixed by https://github.com/iresty/apisix/pull/338

**Comment by moonming** [comment]
@LazyMaple fixed, please try again. thanks

**Comment by LazyMaple** [comment]
@moonming it works, thanks a lot
