### ISSUE TITLE
feature: allow developers to customize the implementation of third-party routers

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#353]
The current route is implemented on the basis of r3. Although it is powerful, it cannot be fully compatible for different user scenarios.

So we also support router plugins, allowing users to implement different routers according to their needs.

目前的路由是在 r3 基础上实现的，虽然它比较强大，不过针对不同用户场景也无法做到全部兼容。

所以我们也支持路由器插件，允许用户根据自身需求实现不同的路由器。

**Comment by moonming** [comment]
now we support radixtree router.

**Comment by membphis** [comment]
APISIX allows users to customize different routers.
