### ISSUE TITLE
 How to dynamically register routes

### ISSUE THREAD

**Issue by snxq** [iresty/apisix#363]

**Comment by membphis** [comment]
This is an example of adding a new route using the limit-count plugin:

https://github.com/iresty/apisix/blob/master/doc/plugins/limit-count.md#enable-plugin

**Comment by snxq** [comment]
@membphis  Thanks for your reply. 

hmm, In another word, Is it support to migrate from nginx to api six?

**Comment by membphis** [comment]
https://github.com/iresty/apisix/blob/master/bin/apisix#L59

You can set your nginx.conf here.  With apisix dynamics and plugin mechanics, you can achieve more powerful features.

**Comment by snxq** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    This way will not save in etcd, those api also not managed by apisix. Right?
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                OliverCh
                            
                    
                        
                            
                                    snxq1995@gmail.com
 
    

    On 08/5/2019 11:19，YuanSheng Wang<notifications@github.com> wrote： 


https://github.com/iresty/apisix/blob/master/bin/apisix#L59
You can set your nginx.conf here.  With apisix dynamics and plugin mechanics, you can achieve more powerful features.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by membphis** [comment]
my qq: 272995614
I think we can talk by IM.

**Comment by membphis** [comment]
> This way will not save in etcd, those api also not managed by apisix. Right?

it's dangerous to save this template by etcd. If we can control this danger, we will support this feature in the future.

**Comment by snxq** [comment]
OK.
