### ISSUE TITLE
feature: abtesting

### ISSUE THREAD

**Issue by xianhuawei** [iresty/apisix#387]
类似 https://github.com/CNSRE/ABTestingGateway/tree/master/lib/abtesting/diversion 这种支持
ip段分流 用户uid段分流 uid尾数分流  uid白名单分流 城市分流

**Comment by xianhuawei** [comment]
abtesting对精细化运营是强需求

**Comment by membphis** [comment]
目前 apisix 是允许插件挂载 balancer 阶段进而实现自己路由的，从而满足上面提到的各种需求。

可以参考这个插件例子，写个插件即可：

https://github.com/iresty/apisix/blob/master/lua/apisix/plugins/example-plugin.lua#L53
