### ISSUE TITLE
[bug] dashboard 显示bug

### ISSUE THREAD

**Issue by wasabihu** [iresty/apisix#388]
我加的id 是指定401的， 但在dashboard 上就显示成41了，这里应该有个小bug~
![bug1](https://user-images.githubusercontent.com/973168/62695664-5da3d200-ba09-11e9-966c-d091290cfbee.png)
![bug2](https://user-images.githubusercontent.com/973168/62695680-6399b300-ba09-11e9-9996-e78fb017c689.png)
![bug3](https://user-images.githubusercontent.com/973168/62695686-65fc0d00-ba09-11e9-9c3f-c19469655864.png)

**Comment by juzhiyuan** [comment]
@wasabihu 已修正，请更新 dashboard_built 仓库。

![image](https://user-images.githubusercontent.com/2106987/62748822-a05abe00-ba8c-11e9-9df7-17b045503e5a.png)

**Comment by moonming** [comment]
@wasabihu fixed, please pull the latest version of dashboard.
