### ISSUE TITLE
Error: Invalid argument: unknown flag --lua-dir. See --help.

### ISSUE THREAD

**Issue by forging2012** [iresty/apisix#407]
sudo luarocks install --lua-dir=/usr/local/openresty/luajit apisix

Error: Invalid argument: unknown flag --lua-dir. See --help.

**Comment by moonming** [comment]
which version of your luarocks?

**Comment by forging2012** [comment]
https://github.com/iresty/apisix/blob/master/doc/install-dependencies.md

Debian 9
# add openresty source
wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y "deb http://openresty.org/package/debian $(lsb_release -sc) openresty"
sudo apt-get update

# install etcd
wget https://github.com/etcd-io/etcd/releases/download/v3.3.13/etcd-v3.3.13-linux-amd64.tar.gz
tar -xvf etcd-v3.3.13-linux-amd64.tar.gz && \
    cd etcd-v3.3.13-linux-amd64 && \
    sudo cp -a etcd etcdctl /usr/bin/

# install openresty and some compilation tools
sudo apt-get install -y git openresty cmake curl luarocks\
    check libpcre3 libpcre3-dev libjemalloc-dev \
    libjemalloc1 build-essential libtool automake autoconf pkg-config

# start etcd server
nohup etcd &



root@n6:~# luarocks --version
/usr/bin/luarocks 2.4.2
LuaRocks main command-line interface


root@n6:~# sudo luarocks install --lua-dir=/usr/local/openresty/luajit apisix

Error: Invalid argument: unknown flag --lua-dir. See --help.

**Comment by moonming** [comment]
`--lua-dir` was first introduced in the luarocks 3.0 release.
please update your luarocks and try again, thx.

**Comment by forging2012** [comment]
All done and push it. https://github.com/iresty/apisix/pull/408
