### ISSUE TITLE
AB Test

### ISSUE THREAD

**Issue by dearjane** [iresty/apisix#448]
我想了解下，基于apisix能不能实现基于uid的ab test

**Comment by moonming** [comment]
sure, APISIX can do AB test.
where is your uid? in the http header, uri args or post body?

**Comment by nic-chen** [comment]
> sure, APISIX can do AB test.
> where is your uid? in the http header, uri args or post body?

cookie or header

**Comment by membphis** [comment]
https://github.com/iresty/lua-resty-radixtree/pull/5/files#diff-b59453348f7312db40e6a5de48f31ff5R114

the `lua-resty-radixtree` supports all nginx variable for  now, that is a powerful feature for user. so it is no problem to support cookie or header.

**Comment by soulsoul** [comment]
That is what I need

**Comment by membphis** [comment]
https://github.com/iresty/apisix/pull/458

apisix has supported this feature now. this PR was merged ^_^

I think you can close this PR.
