### ISSUE TITLE
jwt-auth-cn.md 的帮助文档差点误导我，当然是我看得不够仔细的原因。

### ISSUE THREAD

**Issue by yaojixiang1975** [iresty/apisix#454]
key: 不同的 consumer 对象应有不同的值，它应当是唯一的。不同 consumer 使用了相同的 key ，将会出现请求匹配异常。
所以例子中的 "key": "user-key",改为 "key": "consumer-key" 比较好一点。谢谢

**Comment by moonming** [comment]
pr is welcome

**Comment by membphis** [comment]
fixed already, thx
