### ISSUE TITLE
The configuration used is r3-host-uri with a problem

### ISSUE THREAD

**Issue by sushuai** [iresty/apisix#457]
The configuration I'm using is r3-host-uri, and I set the route's uri to be "/bar/{:\\w+}/{:.*\\.}html” with a test host, the first two requests were successful, and then the request became 404. @membphis

**Comment by membphis** [comment]
please check the version of `lib-resty-libr3`, the latest version is v1.1

**Comment by membphis** [comment]
that is a bug for old version, we fix it for weeks.

**Comment by sushuai** [comment]
ok, thanks.

**Comment by membphis** [comment]
we have fixed this bug, please try apisix 0.7 or latest version of branch `master`.
