### ISSUE TITLE
macOS installation instruction problem

### ISSUE THREAD

**Issue by wangyjx** [iresty/apisix#479]
macOS 10.14.6
using 
sudo luarocks install --lua-dir=/usr/local/openresty/luajit apisix  
encounters error like 
Error: Lua interpreter not found at /usr/local/openresty/luajit

after I had a look at the directory, it turns out the right path should be /usr/local/opt/openresty/luajit 
then the right luarocks install command should be 
luarocks install --lua-dir=/usr/local/opt/openresty/luajit apisix

**Comment by membphis** [comment]
I guess you installed your openresty by brew, you can get the path by command if you installed `openresty`

```shell
$ brew --prefix openresty/brew/openresty
/usr/local/opt/openresty
$ luarocks install --lua-dir=/usr/local/opt/openresty/luajit apisix
Installing https://luarocks.org/apisix-0.7-0.rockspec
Missing dependencies for apisix 0.7-0:
   lua-resty-template 1.9 (not installed)
   lua-resty-etcd 0.6 (not installed)
   lua-resty-ngxvar 0.3 (not installed)
   lua-resty-jit-uuid 0.0.7 (not installed)
   rapidjson 0.6.1 (not installed)
   lua-resty-healthcheck-iresty 1.0.1 (not installed)
   lua-resty-jwt 0.2.0 (not installed)
   lua-resty-cookie 0.1.0 (not installed)
   lua-resty-session 2.24 (not installed)
   opentracing-openresty 0.1 (not installed)
   lua-resty-radixtree 0.7 (not installed)
   lua-resty-iputils 0.3.0-1 (not installed)
... ...
```

**Comment by wangyjx** [comment]
after I ran 
sudo luarocks install --lua-dir=/usr/local/opt/openresty/luajit apisix

error as following:

/usr/local/opt/lua/bin/lua5.3: ...llar/luarocks/3.1.3/share/lua/5.3/luarocks/core/path.lua:17: assertion failed!
stack traceback:
[C]: in function 'assert'
...llar/luarocks/3.1.3/share/lua/5.3/luarocks/core/path.lua:17: in function 'luarocks.path.rocks_dir'
...al/Cellar/luarocks/3.1.3/share/lua/5.3/luarocks/path.lua:216: in function 'luarocks.path.use_tree'
...cal/Cellar/luarocks/3.1.3/share/lua/5.3/luarocks/cmd.lua:105: in upvalue 'process_tree_flags'
...cal/Cellar/luarocks/3.1.3/share/lua/5.3/luarocks/cmd.lua:423: in function 'luarocks.cmd.run_command'
/usr/local/bin/luarocks:38: in main chunk
[C]: in ?

Please advise

**Comment by membphis** [comment]
it seems that luarocks doesn't found the luajit at your computer. do you have wechat or QQ? we can talk by IM. 

my qq: 272995614

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/64426599-8fc85280-d0e1-11e9-89cf-43348d60b9b0.png)

**Comment by wangyjx** [comment]
I send application to your QQ.

here is my result:

brew --prefix openresty/brew/openresty
/usr/local/opt/openresty

and I also double confirm this path, 
there is luajit directory 

COPYRIGHT                     README.markdown               homebrew.mxcl.openresty.plist lualib                        pod                           site
INSTALL_RECEIPT.json          bin                           luajit                        nginx                         resty.index

**Comment by membphis** [comment]
I did not got your request on QQ, what is your QQ number?

**Comment by wangyjx** [comment]
1269192  又发了一次

**Comment by wangyjx** [comment]
非常感谢讲解

**Comment by membphis** [comment]
是我们文档没做好，把你带歪，欢迎补充更新一下文档
