### ISSUE TITLE
[Voting] Promoting @nic-chen as a member of Committer Team 

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#491]
This is first Voting since APISIX Organization begins to work.

**Proposal**
------
@nic-chen is a architect in meizu.com, who help us a lot:

- Implemented gRPC transcoding
- Provide technical suggestions for APISIX
- Running APISIX in meizu.

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on the your contribution, and proposal by one of the existing member.

**Comment by membphis** [comment]
+1

**Comment by moonming** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have two yes. So congrats @nic-chen to join the committer team. I will send the invitation to @nic-chen and update the team list.

Thanks, every one.
