### ISSUE TITLE
[Voting] Promoting @juzhiyuan as a member of Committer Team

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#498]
**Proposal**
------
@juzhiyuan is a freelancer, who help us a lot:

- Implemented dashboard of APISIX
- Provide suggestions for docs

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by moonming** [comment]
+1

**Comment by yuanfeng0905** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by membphis** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have 3 yes. So congrats @juzhiyuan to join the committer team. I will send the invitation to @juzhiyuan and update the team list.

Thanks, every one.
