### ISSUE TITLE
typo in plugin `example-plugin`

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#507]
https://github.com/iresty/apisix/blob/master/lua/apisix/plugins/example-plugin.lua#L54

![image](https://user-images.githubusercontent.com/6814606/64701489-748f8580-d4db-11e9-994a-667c97953183.png)

**Comment by membphis** [comment]
and we need to confirm if other plugins have similar typo.

**Comment by zhiyong0804** [comment]
function _M.balancer(conf, ctx)
    core.log.warn("plugin balancer phase, conf: ", core.json.encode(conf))

    if not conf.ip then
        return
    end

    -- NOTE: update `ctx.balancer_name` is important, APISIX will skip other
    -- balancer handler.
    ctx.balancer_name = plugin_name

    local ok, err = balancer.set_current_peer(conf.ip, conf.port)
    if not ok then
        core.log.error("failed to set server peer: ", err)
        return core.response.exit(502)
    end
end

**Comment by membphis** [comment]
fixed https://github.com/iresty/apisix/commit/799026638e24f4d24aa4b346f613b57c2ceb1123
