### ISSUE TITLE
[Voting] Promoting @chnliyong as a member of Committer Team 

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#519]
**Proposal**
------
@chnliyong is a technical expert of souche.com, who help us a lot:

- Implemented ip-restriction plugin of APISIX
- fixed bugs in test cases
- Provide suggestions for docs

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by membphis** [comment]
+1

**Comment by moonming** [comment]
+1

**Comment by juzhiyuan** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have 4 yes. So congrats @chnliyong to join the committer team. I will send the invitation to @chnliyong and update the team list.

Thanks, every one.
