### ISSUE TITLE
manual develop doc need add install luarocks

### ISSUE THREAD

**Issue by zhiyong0804** [iresty/apisix#525]
If you are a developer, you can set up a local development environment with the following commands.

git clone git@github.com:iresty/apisix.git
cd apisix

/# init submodule
git submodule update --init --recursive

/# install dependency
make dev

-------
on ubuntu OS, need to install luarocks, otherwise there will be flow errors:
lizhiyong@ubuntu:~/source/apisix$ make dev
/bin/sh: 1: luarocks: Permission denied
/bin/sh: 1: luarocks: Permission denied
luarocks install rockspec/apisix-dev-1.0-0.rockspec --tree=deps --only-deps --local
make: execvp: luarocks: Permission denied
Makefile:30: recipe for target 'dev' failed
make: *** [dev] Error 127

so maybe the steps should be:

git clone git@github.com:iresty/apisix.git
cd apisix

/# init submodule
git submodule update --init --recursive

/#ubuntu OS
sudo apt install luarocks

/#centos or debian :
yum install luarocks -y 

/# install dependency
sudo make dev

**Comment by zhiyong0804** [comment]
need to install luarocks

**Comment by membphis** [comment]
I submit a new PR right now: https://github.com/iresty/apisix/pull/526

you can take a look, I think it can help you.
