### ISSUE TITLE
Do we need one new fields to disable upstream node?

### ISSUE THREAD

**Issue by a610569731** [iresty/apisix#532]
需求场景 
替换后端代码需要下线其中某个节点,替换后在上线

------

scenario
upgrading back-end  requires one of the nodes to be offline, and then on-line

**Comment by membphis** [comment]
我们是否可以用 weight = 0 这个特殊的值表明具体某个 node 被禁用的效果呢？

无论是 roundbin 还是 chash，在开始 pick server 之前，都先过滤掉 weight 为 0 的 node 。

**Comment by a610569731** [comment]
可以的

**Comment by membphis** [comment]
你有兴趣自己尝试实现不，还是我来搞呀。核心代码改起来比较容易，有些难度的估计就是测试用例部分

**Comment by a610569731** [comment]
lua 还看不懂哈

**Comment by membphis** [comment]
fixed by https://github.com/iresty/apisix/pull/536
