### ISSUE TITLE
 Requirement: apisix can modify the request header, add the request parameters and modify the request URI before forwarding the client request to the real server

### ISSUE THREAD

**Issue by ygm521** [iresty/apisix#548]

**Comment by moonming** [comment]
@ygm521 sure, APISIX can implement this easily.
You can refer to this PR: https://github.com/iresty/apisix/pull/451.
PR is welcomed.

**Comment by moonming** [comment]
implemented by [rewrite plugin](https://github.com/iresty/apisix/blob/master/doc/plugins/proxy-rewrite.md)
