### ISSUE TITLE
module 'apisix.balancer' not found

### ISSUE THREAD

**Issue by ygm521** [iresty/apisix#554]
**# Environment**
[root@localhost apisix]# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

**install like:**
https://github.com/iresty/apisix/blob/master/doc/dev-manual.md
yum install -y pcre-devel openssl-devel gcc curl
openresty-1.15.8.2
pcre-8.40.tar.gz
cd  openresty-1.15.8.2;./configure --with-pcre=../pcre-8.40 --with-pcre-jit --with-http_stub_status_module --with-http_realip_module --with-http_v2_module -j4

[root@localhost apisix]# make init
./bin/apisix init
./bin/apisix init_etcd
[root@localhost apisix]# make run
mkdir -p logs
mkdir -p /tmp/apisix_cores/

**err:**
2019/09/22 18:59:58 [error] 97070#0: init_worker_by_lua error: /home/wbq/source/six/apisix/lua/apisix.lua:62: module 'apisix.balancer' not found:

**if used apisix-0.7:**
2019/09/22 19:24:55 [error] 101272#0: init_worker_by_lua error: /home/wbq/source/six/apisix-0.7/lua/apisix.lua:54: module 'apisix.http.balancer' not found:
        no field package.preload['apisix.http.balancer']
        no file '/home/wbq/source/six/apisix-0.7//deps/share/lua/5.1/apisix/http/balancer.lua'
        no file '/home/wbq/source/six/apisix-0.7/lua/apisix/http/balancer.lua'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer/init.ljbc'
        no file '/usr/local/openresty/lualib/apisix/http/balancer.ljbc'
        no file '/usr/local/openresty/lualib/apisix/http/balancer/init.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer.lua'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer/init.lua'
        no file '/usr/local/openresty/lualib/apisix/http/balancer.lua'
        no file '/usr/local/openresty/lualib/apisix/http/balancer/init.lua'

**if used openresty1.15.8.1 with apisix-0.7 also：**
2019/09/22 19:24:55 [error] 101272#0: init_worker_by_lua error: /home/wbq/source/six/apisix-0.7/lua/apisix.lua:54: module 'apisix.http.balancer' not found:
        no field package.preload['apisix.http.balancer']
        no file '/home/wbq/source/six/apisix-0.7//deps/share/lua/5.1/apisix/http/balancer.lua'
        no file '/home/wbq/source/six/apisix-0.7/lua/apisix/http/balancer.lua'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer/init.ljbc'
        no file '/usr/local/openresty/lualib/apisix/http/balancer.ljbc'
        no file '/usr/local/openresty/lualib/apisix/http/balancer/init.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/http/balancer.lua'

**Comment by membphis** [comment]
The problem should be with access rights. You use the nginx worker process started by the root user to access other user user files, most likely failing because there is no file read permission.

You can delete the `deps` files first, switch to the normal user, `make dev` again, rebuild the `deps`, and then start it, it'll be fine.

**Comment by ygm521** [comment]
thank you!


 
---Original---

**Comment by membphis** [comment]
can we close this issue? @ygm521
