### ISSUE TITLE
[Voting] Promoting @linsir as a member of Committer Team

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#559]
**Proposal**
------
@linsir is an ops of axinfu.com, who help us a lot:

- fixed bugs in apisix-docker
- fixed typo in lua-resty-radixtree and lua-resty-libr3 docs

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by moonming** [comment]
+1

**Comment by membphis** [comment]
+1

**Comment by chnliyong** [comment]
+1

**Comment by juzhiyuan** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have 5 yes. So congrats @linsir to join the committer team. I will send the invitation to @linsir and update the team list.

Thanks, every one.
