### ISSUE TITLE
[Voting] Promoting @supermario1990 as a member of Committer Team

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#562]
**Proposal**
------
@supermario1990 is Senior Development Engineer of szrhtj.com, who help us a lot:

- fixed typo in APISIX
- provide technical suggestions for APISIX

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by moonming** [comment]
+1

**Comment by membphis** [comment]
+1

**Comment by chnliyong** [comment]
+1

**Comment by juzhiyuan** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have 5 yes. So congrats @supermario1990 to join the committer team. I will send the invitation to @supermario1990 and update the team list.

Thanks, every one.
