### ISSUE TITLE
[Voting] Promoting @zhiyong0804 as a member of Committer Team

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#563]
**Proposal**
------
@zhiyong0804  is Development Engineer of  Hunan Zero Sound Information Technology Co., Ltd., who help us a lot:

- fixed typo in APISIX
- provide technical suggestions for APISIX
- answer many questions in APISIX's dev group

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by moonming** [comment]
+1

**Comment by chnliyong** [comment]
+1

**Comment by juzhiyuan** [comment]
+1

**Comment by membphis** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by moonming** [comment]
all @iresty/pmc and @iresty/committer-team have voted. And we have 5 yes. So congrats @zhiyong0804 to join the committer team. I will send the invitation to @zhiyong0804 and update the team list.

Thanks, every one.
