### ISSUE TITLE
change: implement a new plugin, to modify scheme, uri, host and enable_websocket.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#569]
we can change `scheme`, `uri`, `host` and `enable_websocket` when we create a new upstream object now, this is not appropriate.

They should not be upstream attributes and should exist independently. We should also allow different uri values to be set for the same upstream.

在当前方案中，我们可以在创建 upstream 对象时指定 `scheme`, `uri`, `host` and `enable_websocket` 等值，这是不合适的。

这些不应当是 upstream 的属性。比如同一个上游，不同请求下应当允许被设置成不同 uri 。

**Comment by shuaijinchao** [comment]
agree with this, Using plugins to complete this function can achieve better scalability.
