### ISSUE TITLE
request help: the development environment,when make run,reported an error

### ISSUE THREAD

**Issue by tomzhan2019** [iresty/apisix#571]
2019/09/21 07:45:15 [error] 66277#66277: init_worker_by_lua error: /data/apisix/lua/apisix.lua:62: module 'apisix.balancer' not found:
        no field package.preload['apisix.balancer']
        no file '/data/apisix//deps/share/lua/5.1/apisix/balancer.lua'
        no file '/data/apisix/lua/apisix/balancer.lua'
        no file '/usr/local/openresty/site/lualib/apisix/balancer.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/balancer/init.ljbc'
        no file '/usr/local/openresty/lualib/apisix/balancer.ljbc'
        no file '/usr/local/openresty/lualib/apisix/balancer/init.ljbc'
        no file '/usr/local/openresty/site/lualib/apisix/balancer.lua'
        no file '/usr/local/openresty/site/lualib/apisix/balancer/init.lua'
        no file '/usr/local/openresty/lualib/apisix/balancer.lua'
        no file '/usr/local/openresty/lualib/apisix/balancer/init.lua'
        no file './apisix/balancer.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/balancer.lua'
        no file '/usr/local/share/lua/5.1/apisix/balancer.lua'
        no file '/usr/local/share/lua/5.1/apisix/balancer/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/balancer.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/balancer/init.lua'
        no file '/data/apisix/lua/apisix/balancer.lua'
        no file '/data/apisix/deps/share/lua/5.1/apisix/balancer.lua'
        no file './apisix/balancer.lua'
        no file '/usr/share/lua/5.1/apisix/balancer.lua'
        no file '/usr/share/lua/5.1/apisix/balancer/init.lua'
        no file '/usr/lib64/lua/5.1/apisix/balancer.lua'
        no file '/usr/lib64/lua/5.1/apisix/balancer/init.lua'
        no file '/data/apisix//deps/lib64/lua/5.1/apisix/balancer.so'
        no file '/data/apisix//deps/lib/lua/5.1/apisix/balancer.so'
        no file '/usr/local/openresty/site/lualib/apisix/balancer.so'
        no file '/usr/local/openresty/lualib/apisix/balancer.so'
        no file './apisix/balancer.so'
        no file '/usr/local/lib/lua/5.1/apisix/balancer.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/balancer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/data/apisix/deps/lib64/lua/5.1/apisix/balancer.so'
        no file './apisix/balancer.so'
        no file '/usr/lib64/lua/5.1/apisix/balancer.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
        no file '/data/apisix//deps/lib64/lua/5.1/apisix.so'
        no file '/data/apisix//deps/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/site/lualib/apisix.so'
        no file '/usr/local/openresty/lualib/apisix.so'
        no file './apisix.so'
        no file '/usr/local/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/data/apisix/deps/lib64/lua/5.1/apisix.so'
        no file './apisix.so'
        no file '/usr/lib64/lua/5.1/apisix.so'
        no file '/usr/lib64/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /data/apisix/lua/apisix.lua:62: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

**Comment by membphis** [comment]
please check if the file path is right. 

and how do you run the apisix server? start the apisix server by normal user or root?

```
no file '/data/apisix//deps/share/lua/5.1/apisix/balancer.lua'
no file '/data/apisix/lua/apisix/balancer.lua'
```

**Comment by tomzhan2019** [comment]
The problem has been solved, please refer to https://github.com/iresty/apisix/issues/554.
