### ISSUE TITLE
request help: When apisix is started by default, will the file descriptor be 1024 or will it be automatically set to 65535 or higher?

### ISSUE THREAD

**Issue by Miss-you** [iresty/apisix#588]
# Issue description
apisix默认启动的时候，文件描述符是1024还是会自动设置成65535或者更高？

# Environment

* apisix version (cmd: `apisix version`):0.7.0或者更高
* OS:

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by moonming** [comment]
APISIX does not modify any system-related configuration. So the value of `ulimit` is only depends on you.

**Comment by kerneltravel** [comment]
@Miss-you you can manually set ulimit value before start apisix process, by add
```
LimitNOFILE=65535
```
before 
```
ExecStart=/usr/bin/apisix start
```
to systemd service file  `/usr/lib/systemd/system/apisix.service` , 
and run `systemctl daemon-reload` and `systemctl restart apisix ` to take effect.

referer info : https://unix.stackexchange.com/questions/345595/how-to-set-ulimits-on-service-with-systemd
