### ISSUE TITLE
bug: can not run APISIX on the ARM platfrom (centos 7)

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#589]
# Issue description
APISIX run error on the ARM platform

# Environment
APISIX 0.7 RPM package
huawei cloud kc1.small.1
CentOS 7.6 64bit with ARM

# Minimal test code / Steps to reproduce the issue
```
sudo apisix start
```

# What's the actual result? (include assertion message & call stack if applicable)
[root@ecs-arm ~]# sudo apisix start
nginx: [error] init_by_lua error: error loading module 'rapidjson' from file '/usr/local/apisix//deps/lib64/lua/5.1/rapidjson.so':
	/usr/local/apisix//deps/lib64/lua/5.1/rapidjson.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0xffff8ef4c5c0
	[C]: in function 'require'
	/usr/local/apisix/lua/apisix/core/schema.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/lua/apisix/core/config_etcd.lua:9: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/lua/apisix/core.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/apisix/lua/apisix.lua:4: in main chunk
	[C]: in function 'require'
	init_by_lua:3: in main chunk

# What's the expected result?

**Comment by soulsoul** [comment]
file miss？

**Comment by moonming** [comment]
> file miss？

```
# ll /usr/local/apisix//deps/lib64/lua/5.1/rapidjson.so
-rwxr-xr-x 1 root root 2659990 9月   6 17:32 /usr/local/apisix//deps/lib64/lua/5.1/rapidjson.so
```
the file is exist.

**Comment by moonming** [comment]
`lua-rapidjson` built failed by manual in ARM: https://github.com/xpol/lua-rapidjson/issues/44
I think the RPM package can not use directly in ARM server.

**Comment by moonming** [comment]
https://github.com/Tencent/rapidjson/issues/1574

**Comment by moonming** [comment]
APISIX supported ARM64 in ubuntu 18.04, huawei kunpeng CPU: https://mp.weixin.qq.com/s/ZulGGzQRbi23lTvEAbqr6w

**Comment by moonming** [comment]
we removed rapidjson, so I think APISIX supports ARM64 centos now.
