### ISSUE TITLE
bug: Individual work memory usage is abnormal

### ISSUE THREAD

**Issue by buhejiudewangxiansheng** [iresty/apisix#590]
# Issue description
Individual work memory usage is abnormal

# Environment

* apisix version (cmd: `apisix version`): v0.7
* OS:centos7

# Minimal test code / Steps to reproduce the issue

curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/hel*",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?

**Comment by membphis** [comment]
There should be a memory overflow for the prefix match of radixtree, I am working for it.
