### ISSUE TITLE
doc(admin api): API description about `routes`.

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#592]
like this:

![image](https://user-images.githubusercontent.com/6814606/65587154-f5f51680-dfb7-11e9-8a26-e3221c383435.png)

**Comment by juzhiyuan** [comment]
@membphis Do we need a website for Doc of APISIX like https://docsify.js.org/#/quickstart ?

**Comment by membphis** [comment]
@juzhiyuan of course we need this, that is our a big todo.

**Comment by juzhiyuan** [comment]
We can implement the site like that just by some simple steps.

**Comment by moonming** [comment]
@juzhiyuan you can add a new repo to implement the doc site.

**Comment by juzhiyuan** [comment]
@moonming I don't have the proper permissions to create a new Repo under iResty

![image](https://user-images.githubusercontent.com/2106987/65656637-276ef000-e053-11e9-8bda-c253f012d20c.png)

**Comment by membphis** [comment]
> @moonming I don't have the proper permission to create a new Repo under iResty
> 
> ![image](https://user-images.githubusercontent.com/2106987/65656637-276ef000-e053-11e9-8bda-c253f012d20c.png)

you can leave a repo name here, we'll help you to create it.

**Comment by juzhiyuan** [comment]
I'd like to call the repo `apisix-doc`

**Comment by membphis** [comment]
already done: https://github.com/iresty/apisix-doc

**Comment by moonming** [comment]
@juzhiyuan you have the write access for apisix-doc repo now.
