### ISSUE TITLE
bug:  install script fail without any hint

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#596]
if user not install openresty or not add `openresty` to the ENV, this install script will fail without any hint:
https://github.com/iresty/apisix/blob/master/utils/install-apisix.sh#L6 

```
# sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/iresty/apisix/master/utils/install-apisix.sh)"
+ which openresty
+ OR_EXEC=
```

**Comment by soulsoul** [comment]
let me do it

**Comment by moonming** [comment]
@soulsoul thx. you can assign this issue to yourself.
