### ISSUE TITLE
API schema validation

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#6]
the goal:

- code simplicity, we may add new feature to it
- open source and good performance
- pure Lua if possible

how about this: 

-- JSON schema validation
https://github.com/jdesgats/ljsonschema
https://github.com/epoberezkin/ajv

**Comment by tianchaijz** [comment]
Maybe you can try my https://github.com/tianchaijz/lua-resty-jsonschema validator.

**Comment by membphis** [comment]
https://github.com/Tencent/rapidjson/blob/master/example/schemavalidator/schemavalidator.cpp

This is also a good alternative.

**Comment by membphis** [comment]
implemented already: https://github.com/iresty/apisix/commit/1737fb702e6b6537d3c7198f859e72d4060b5fc1
