### ISSUE TITLE
Feature apisix-doc

### ISSUE THREAD

**Issue by juzhiyuan** [iresty/apisix#605]
@moonming @membphis 

I will use [docsify](https://docsify.js.org/#/quickstart) to help us build the doc site. And following steps are my ways to implement it:

1. Migrate files under `apisix/doc` to repo `apisix-doc`, or copy files' content from `apisix/doc` to repo `apisix-doc`;
2. Expand the usage of every plugin like https://docs.rsshub.app/new-media.html;

Do we have some special rules or requirements about the doc site?

**Comment by juzhiyuan** [comment]
Also, I will build the English site first.

**Comment by moonming** [comment]
I think we can keep doc in `apisix` at first, which is better for community cooperation.
Sure, I agree with the English first.

**Comment by juzhiyuan** [comment]
Yep, it's a good idea to let contributors update doc in the apisix repo.
