### ISSUE TITLE
featrue: support connect to redis cluster

### ISSUE THREAD

**Issue by soulsoul** [iresty/apisix#607]

**Comment by moonming** [comment]
can you explain the scenarios why we need to connect redis cluster?  thx

**Comment by soulsoul** [comment]
for the global parameter store for some  compute scense , like the global rate limit and some  statistics .

**Comment by wangyjx** [comment]
> for the global parameter store for some compute scense , like the global rate limit and some statistics .

etcd also has key-value store function, why not use it?

**Comment by moonming** [comment]
worry about the performance of etcd

**Comment by membphis** [comment]
feature `global rate limit`,  we can implement it with redis, the single redis should be enough.

**Comment by soulsoul** [comment]
stand-alone does not have high availability

**Comment by moonming** [comment]
I don't think we should care about these details directly. They are not the core of the API gateway.
We can use other projects to do, for example: https://github.com/lyft/ratelimit

**Comment by moonming** [comment]
https://github.com/ledgetech/lua-resty-redis-connector  supports redis Sentinel, which is enough for redis HA.

**Comment by moonming** [comment]
already support global limit count plugin:https://github.com/iresty/apisix/blob/master/doc/plugins/limit-count.md, and use redis not the redis cluster. I think redis is enough for me.
