### ISSUE TITLE
Please consider using `lua-resty-master` framework

### ISSUE THREAD

**Issue by tianchaijz** [iresty/apisix#61]
[lua-resty-mater](https://github.com/openresty-fan/lua-resty-master) is a framework for OpenResty development. Please check out my presentation https://github.com/openresty-fan/2017-12-23-openresty-meetup-presentation, if the API gateway is complicated, which might light you up.

**Comment by membphis** [comment]
`apisix` needs to support hot loading, sorting according to plugin priority and other advanced features, `lua-resty-master` is not suitable.
