### ISSUE TITLE
add test cases for plugins.

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#62]
- [x] round-robin balance
- [x] consistent balance
- [x] prometheus

- [x] key-auth

- [x] limit-conn

- [x] limit-req
- [x] limit-count

**Comment by membphis** [comment]
- [ ] round-robin balance
- [ ] consistent balance
- [ ] prometheus

- [ ] key-auth

- [ ] limit-conn

- [ ] limit-req
- [ ] limit-count
