### ISSUE TITLE
[Voting] Promoting @shuaijinchao as a member of Committer Team 

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#623]
**Proposal**
------
@shuaijinchao is Development Engineer of TAL, who help us a lot:

- implemented proxy-rewirte plugin

Please vote for promoting.  @iresty/pmc @iresty/committer-team 

Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain".

------
All contributors have the chance to join PMC or committer team, which depends on your contribution, and a proposal by one of the existing member.

**Comment by linsir** [comment]
agree, yes, +1

**Comment by moonming** [comment]
+1

**Comment by totemofwolf** [comment]
plus 1

**Comment by chnliyong** [comment]
+1

**Comment by juzhiyuan** [comment]
+1

**Comment by zhiyong0804** [comment]
+1

**Comment by nic-chen** [comment]
+1

**Comment by soulsoul** [comment]
+1

**Comment by membphis** [comment]
+1

**Comment by moonming** [comment]
9 of 11 committers have voted. And we have 9 yes. 
So congrats @shuaijinchao to join the committer team. I will send the invitation to @shuaijinchao and update the team list.

Thanks, everyone.
