### ISSUE TITLE
How apisix listen multiple ports?

### ISSUE THREAD

**Issue by hegphegp** [iresty/apisix#634]
# Issue description
* Use nginx, if you want to listen multiple ports , you can configure multiple conf files in /etc/nginx/conf.d file path, each file listens a single port
* How apisix listen multiple ports ?

**Comment by moonming** [comment]
@hegphegp please use English, thx.
For your question, APISIX not support listen multiple ports now, however, you can add code to support that: https://github.com/iresty/apisix/blob/master/conf/config.yaml#L2 and https://github.com/iresty/apisix/blob/master/bin/apisix#L110
