### ISSUE TITLE
discard args of uri when using proxy-write plugin

### ISSUE THREAD

**Issue by KowloonZh** [iresty/apisix#635]
# Issue description
我使用 proxy-write 插件时，将原来的 url: /old/path 重写到新的 url：  /new/path，但是我的请求是有参数的 /old/path?id=2，rewrite 之后参数就没有了，改成 post 请求才可以，请问这个应该如何解决呢？

# Environment

* apisix version (cmd: `apisix version`): 0.7
* OS: docker Debian Linux 9

# What's the actual result? (include assertion message & call stack if applicable)

# What's the expected result?
希望转发 get 请求时，保留原来的参数

**Comment by moonming** [comment]
@shuaijinchao please take a look.  I think we should separate args from URI, user can only rewrite uri without args, and add more doc for that.

**Comment by moonming** [comment]
@KowloonZh I think it's a bug. we will fix it later.

**Comment by KowloonZh** [comment]
> @KowloonZh I think it's a bug. we will fix it later.

感谢温老师，既然你们要修改的话，能不能再加上 upstream_timeout 字段（我们目前的业务是默认的接口超时时间是 10s，但是也允许部分接口单独设置超时时间），这样我们就不用重写这个插件了

**Comment by moonming** [comment]
@KowloonZh APISIX already support timeouts of upstream: https://github.com/iresty/apisix/blob/master/lua/apisix/schema_def.lua#L221.

**Comment by shuaijinchao** [comment]
OK, I will deal with this problem as soon as possible.
