### ISSUE TITLE
change the name of dev rockspec

### ISSUE THREAD

**Issue by moonming** [iresty/apisix#647]
change the name of https://github.com/iresty/apisix/blob/master/rockspec/apisix-dev-1.0-0.rockspec from `dev-1.0` to `master`.

**Comment by soulsoul** [comment]
@moonming   the rockspec file expected filename in format 'name-version-revision.rockspec', and the version field must match type "[%w.]+-[%d]+".  so the name maybe should named "master-1.0" , ok?

**Comment by moonming** [comment]
looks good to me.

**Comment by soulsoul** [comment]
"master-0"  is commited
