### ISSUE TITLE
qps is low: four core CPUs have only about 40,000 QPS

### ISSUE THREAD

**Issue by membphis** [iresty/apisix#654]
routes:

```json
[{
	"hosts": "me.bz.foo.com",
	"handler": "function: 0x1752fad8",
	"paths": "\/moc.oof.zb.em\/*"
}, {
	"hosts": "credits.bz.foo.com",
	"handler": "function: 0x1752fcb8",
	"paths": "\/moc.oof.zb.stiderc\/*"
}, {
	"hosts": "credits-beta.bz.foo.com",
	"handler": "function: 0x1752fe90",
	"paths": "\/moc.oof.zb.ateb-stiderc\/*"
}, {
	"hosts": "homepage.bz.foo.com",
	"handler": "function: 0x17530080",
	"paths": "\/moc.oof.zb.egapemoh\/*"
}]
```

**Comment by bobopan** [comment]
apisix v0.8

`curl http://127.0.0.1:9080/apisix/admin/upstreams/1 -X PUT -d '
{
    "type": "roundrobin",
    "nodes": {
        "127.0.0.2:80": 1
    }
}'`

`
curl http://127.0.0.1:9080/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/*",
    "host": "me.bz.foo.com",
    "upstream_id": 1
}'
curl http://127.0.0.1:9080/apisix/admin/routes/2 -X PUT -d '
{
    "uri": "/*",
    "host": "homepage.bz.foo.com",
    "upstream_id": 1
}'
curl http://127.0.0.1:9080/apisix/admin/routes/3 -X PUT -d '
{
    "uri": "/*",
    "host": "credits.bz.foo.com",
    "upstream_id": 1
}'

curl http://127.0.0.1:9080/apisix/admin/routes/4 -X PUT -d '
{
    "uri": "/*",
    "host": "task.bz.foo.com",
    "upstream_id": 1
}'
`

run wrk:
wrk -t4 -c200 -d30s --latency  "http://credits.bz.foo.com/hello"

QPS:48037

used 4 cores to run APISIX

**Comment by bobopan** [comment]
server {
	listen 9080;
	location / {
		proxy_pass http://credits;
proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_set_header X-Scheme $scheme;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Myreferer $arg_referer;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
	}
    }

**Comment by membphis** [comment]
we submitted a new router for this case: https://github.com/iresty/apisix/pull/671
