### ISSUE TITLE
bug: route.value.id will be replaced with service.id when call the func merge_service_route 

### ISSUE THREAD

**Issue by KowloonZh** [iresty/apisix#675]
### Issue description
我在插件中需要用到 ctx.matched_route 的 id，但是在文件 lua/apisix/plugin.lua:327，当调用函数 merge_service_route 之后，route 的 id 会被替换为 service  的 id

### Environment

* apisix version (cmd: `apisix version`): 0.7
* OS: debian

### Minimal test code / Steps to reproduce the issue

# your steps
1. 

![image](https://user-images.githubusercontent.com/15882688/66643208-d6fdb200-ec50-11e9-9386-dc5586312528.png)

2.
![image](https://user-images.githubusercontent.com/15882688/66643318-03b1c980-ec51-11e9-8ec8-30d5560520df.png)

图中的 route 是打印的 ctx.matched_route
3.

### What's the expected result?
期待当前 route 与 service 做 merge 时，只替换插件，其他的信息保留，其实这里以 route 为主，来做 merge 是不是更好一点

**Comment by membphis** [comment]
that is a but, we should to fix it.

**Comment by membphis** [comment]
I recheck this bug right now, and I think the current implement is ok.

Take a look at this code: https://github.com/iresty/apisix/blob/master/lua/apisix/plugin.lua#L318

If `new_service_conf` is empty, it will return `service_conf`. Returns `service_conf` directly is a simple method when there are no new plugin configurations, upstream or upstream IDs in the Route.

**Comment by KowloonZh** [comment]
@membphis 

hi, membphis

i do review the code, but i still think it is a bug, cause  i need the origin id of the route but it's changed when merged with service_conf. 

i forked the repo in my github, could you please take a look ath this code:
https://github.com/KowloonZh/apisix/commit/5d7d999c77dc6ac6a7c5a5071e3ff3186f7938eb

by the way, my english is not very good, please forgive me.

**Comment by membphis** [comment]
Why do you need the original route id here? Is there any specific reason? I think we can communicate through IM tools, such as QQ: 272995614.

I just reviewed your code, and every time call `deepcopy` will affect performance, there are no other issues.

**Comment by KowloonZh** [comment]
i sent my wechat account to your email

**Comment by moonming** [comment]
@KowloonZh @membphis please discuss in the public channel, so other people can also help and learn.

**Comment by KowloonZh** [comment]
hi, membphis

the following code in my project is used to check if the current user can access the current route after checking user exists.

```
    -- 5. check if can access the route
    local action_ids = value.action_ids   -- action_ids is all the route ids what the current user owner
    local route = ctx.matched_route
    local from = ngx.re.find(action_ids, ',' .. route.value.id .. ',')
    if from == nil then
        return 401, { message = "auth failed" }
    end
```

**Comment by membphis** [comment]
ok, you can submit a new PR about this case, and please added some related test cases, here is the example: https://github.com/iresty/apisix/blob/6b875cec339e35cf6731cbf52431e0ecf26218f0/t/node/merge-route.t
