### ISSUE TITLE
doc: maybe a mistake in architecture-design-cn.md

### ISSUE THREAD

**Issue by orangle** [iresty/apisix#71]
In this section https://github.com/iresty/apisix/blob/master/doc/architecture-design-cn.md#consumer

Consumer 是某类具体服务的消费者，主要用来表述不同用户的概念。比如**不用**的客户请求同一个 API， 经过用户认证体系，网关服务需知道当前请求用户身份信息，针对不同的消费用户，会有不同的限制处理逻辑。

不用 maybe 不同 ？

**Comment by moonming** [comment]
@orangle thanks, PR is welcome :)
