### ISSUE TITLE
bug:  radixtree_host_uri error

### ISSUE THREAD

**Issue by zihaogs** [iresty/apisix#721]
### Issue description

`coroutine 0:
        /usr/local/apisix/deps/share/lua/5.1/apisix/lua/apisix.lua: in function 'http_access_phase'
        access_by_lua(nginx.conf:134):2: in main chunk, client: 192.168.100.201, server: , request: "GET / HTTP/1.1", host: "www.test.com:9080"
2019/10/22 09:07:11 [error] 97#97: *5792 lua entry thread aborted: runtime error: /usr/local/apisix/deps/share/lua/5.1/apisix/lua/apisix.lua:250: attempt to index field 'router_http' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/apisix/deps/share/lua/5.1/apisix/lua/apisix.lua: in function 'http_access_phase'
        access_by_lua(nginx.conf:134):2: in main chunk, client: 192.168.100.201, server: , request: "GET / HTTP/1.1", host: "www.test.com:9080"`

### Environment

* apisix version (cmd: `apisix version`): 0.8
* OS:docker

### Minimal test code / Steps to reproduce the issue

# your steps
edit config.yaml
router ->  http ->  radixtree_host_uri

**Comment by moonming** [comment]
0.8 version not support ` radixtree_host_uri` yet, please try the master branch, thx

**Comment by zihaogs** [comment]
en .master is ok
