### ISSUE TITLE
request dashboard return 500 err

### ISSUE THREAD

**Issue by xym808** [iresty/apisix#726]
### Issue description
部署参考：https://github.com/iresty/apisix/blob/master/doc/dev-manual-cn.md
访问：curl http://127.0.0.1:9080/apisix/dashboard/
返回：500 错误

### Environment
CentOS Linux release 7.3.1611 (Core) 

* apisix version (cmd: `apisix version`):
* OS:  0.8

### Minimal test code / Steps to reproduce the issue
0.https://github.com/iresty/apisix/blob/master/doc/dev-manual-cn.md（make run last）
1.curl http://127.0.0.1:9080/apisix/dashboard/
2. 500 err
3.

### What's the actual result? (including assertion message & call stack if applicable)
2019/10/22 23:11:58 [crit] 28693#28693: *9 open() "/root/xym/apisix/dashboard/" failed (13: Permission denied), client: 127.0.0.1, server: , request: "GET /apisix/dashboard HTTP/1.1", host: "127.0.0.1:9080"
2019/10/22 23:11:58 [crit] 28693#28693: *9 open() "/root/xym/apisix/dashboard/" failed (13: Permission denied), client: 127.0.0.1, server: , request: "GET /apisix/dashboard HTTP/1.1", host: "127.0.0.1:9080"
2019/10/22 23:11:58 [error] 28693#28693: *9 lua entry thread aborted: runtime error: /root/xym/apisix/lua/apisix.lua:250: attempt to index field 'router_http' (a nil value)
stack traceback:
coroutine 0:
	/root/xym/apisix/lua/apisix.lua: in function 'http_access_phase'
	access_by_lua(nginx.conf:144):2: in main chunk, client: 127.0.0.1, server: , request: "GET /apisix/dashboard HTTP/1.1", host: "127.0.0.1:9080"

**Comment by membphis** [comment]
Nginx The default worker does not have permission to read the /root/ directory privilege. There are two ways to solve it:

1. Put it in another directory, for example: /user/local/apisix
2. Add the user directive to the nginx configuration file
