### ISSUE TITLE
plugin.lua crash

### ISSUE THREAD

**Issue by wangpengdc** [iresty/apisix#82]
![图片](https://user-images.githubusercontent.com/41184903/59402648-eb7c8b80-8dd1-11e9-826d-96963bac3c15.png)

I think, should not be caused by fetching things from an empty table, whatevery the etcd config bad or right

**Comment by membphis** [comment]
we'll add more test cases to cover this case, will fix it soon

**Comment by membphis** [comment]
here is full list:

- [ ] route: https://github.com/iresty/apisix/pull/91

- [ ] service

- [ ] upstream

- [ ] consumer

- [ ] plugin

**Comment by membphis** [comment]
created related single issues already, so we can close this issue now.
